architect:
  - yegor256
docker:
  image: yegor256/rultor-image:1.21.0
assets:
  settings.xml: yegor256/home#assets/antlr2ebnf-maven-plugin/settings.xml
  pubring.gpg: yegor256/home#assets/pubring.gpg
  secring.gpg: yegor256/home#assets/secring.gpg
install: |
  pdd --file=/dev/null
merge:
  script: |
    mvn clean install -Pqulice --errors -Dstyle.color=never
release:
  script: |-
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    mvn versions:set "-DnewVersion=${tag}" -Dstyle.color=never
    git commit -am "${tag}"
    mvn clean install -Dinvoker.skip
    mvn clean deploy -Pantlr2ebnf -Psonatype --errors --settings ../settings.xml -Dstyle.color=never
