---
name: mvn
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  mvn:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-12, windows-2022]
        java: [17]
    steps:
      - uses: actions/checkout@v4
      - uses: teatimeguest/setup-texlive-action@v3.0.2
        with:
          update-all-packages: true
          packages: scheme-basic geometry xcolor naive-ebnf microtype etoolbox
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-jdk-${{ matrix.java }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-jdk-${{ matrix.java }}-maven-
      - run: java -version
      - run: mvn -version
      - run: mvn --errors --batch-mode clean install -Pqulice
